#!/usr/bin/env bash
set -euo pipefail
export SPARK_TEXT_PORT="${SPARK_TEXT_PORT:-8000}"
export SPARK_COACH_PORT="${SPARK_COACH_PORT:-8001}"
export SPARK_STEPAUDIO_BACKEND_PORT="${SPARK_STEPAUDIO_BACKEND_PORT:-8010}"
export SPARK_STEPAUDIO_WS_PORT="${SPARK_STEPAUDIO_WS_PORT:-8092}"
export SPARK_STEPAUDIO_HEALTH_PORT="${SPARK_STEPAUDIO_HEALTH_PORT:-8093}"
export SPARK_RETRIEVER_PORT="${SPARK_RETRIEVER_PORT:-7670}"
export SPARK_VECTORDB_PORT="${SPARK_VECTORDB_PORT:-7671}"
export SPARK_BACKEND_PORT="${SPARK_BACKEND_PORT:-4174}"
export SPARK_AGENT_TOOL_PORT="${SPARK_AGENT_TOOL_PORT:-4175}"
